const userTypeAction = {
    FK_RW_ID: 'FK_RW_ID',
    ID_USER: 'ID_USER',
    NAMA_USER: 'NAMA_USER',
    HP_USER: 'HP_USER',
    EMAIL_USER: 'EMAIL_USER',
    ALAMAT_USER: 'ALAMAT_USER',
    PASSWORD_USER: 'PASSWORD_USER',
    KONF_PASSWORD_USER: 'KONF_PASSWORD_USER',
    TOKEN_USER: 'TOKEN_USER',
    IS_LOGED: 'IS_LOGED',
    LATITUDE_REGISTER: 'LATITUDE_REGISTER',
    LONGTITUDE_REGISTER: 'LONGTITUDE_REGISTER',
    LATITUDE_DINAMIS: 'LATITUDE_DINAMIS',
    LONGTITUDE_DINAMIS: 'LONGTITUDE_DINAMIS',
    LOCATION: 'LOCATION'
}

export default userTypeAction;